import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Obsidian syntax","description":"","frontmatter":{"title":"Obsidian syntax","sidebarTitle":"Obsidian syntax","order":5,"tags":["guide","syntax"]},"headers":[],"relativePath":"guide/docs/obsidian-syntax.md","filePath":"guide/docs/obsidian-syntax.md"}');
const _sfc_main = { name: "guide/docs/obsidian-syntax.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="obsidian-syntax" tabindex="-1">Obsidian syntax <a class="header-anchor" href="#obsidian-syntax" aria-label="Permalink to &quot;Obsidian syntax&quot;">​</a></h1><p>Full demo on the <code>/tour/v0.3-tour</code> page; this is the cheatsheet.</p><h2 id="wikilinks" tabindex="-1">Wikilinks <a class="header-anchor" href="#wikilinks" aria-label="Permalink to &quot;Wikilinks&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Form</th><th>Meaning</th></tr></thead><tbody><tr><td><code>[[note]]</code></td><td>Plain link</td></tr><tr><td><code>[[note|alias]]</code></td><td>Custom text</td></tr><tr><td><code>[[note#heading]]</code></td><td>Anchor jump</td></tr><tr><td><code>[[note#heading|alias]]</code></td><td>Both</td></tr><tr><td><code>[[folder/note]]</code></td><td>Path form</td></tr></tbody></table><p>frontmatter <code>aliases:</code> also participates in resolution.</p><h2 id="embeds" tabindex="-1">Embeds <a class="header-anchor" href="#embeds" aria-label="Permalink to &quot;Embeds&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Form</th><th>Renders</th></tr></thead><tbody><tr><td><code>![[img.png]]</code> / <code>![[img.png|400]]</code> / <code>![[img.png|alt|400x300]]</code></td><td><code>&lt;img&gt;</code></td></tr><tr><td><code>![[clip.mp3]]</code></td><td><code>&lt;audio controls&gt;</code></td></tr><tr><td><code>![[movie.mp4|640x360]]</code></td><td><code>&lt;video controls&gt;</code></td></tr><tr><td><code>![[doc.pdf|800x900]]</code></td><td><code>&lt;iframe&gt;</code></td></tr><tr><td><code>![[note]]</code> / <code>![[note#heading]]</code></td><td>transclusion (inline full / section)</td></tr></tbody></table><h2 id="callouts" tabindex="-1">Callouts <a class="header-anchor" href="#callouts" aria-label="Permalink to &quot;Callouts&quot;">​</a></h2><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">&gt; [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-light-text-decoration": "underline", "--shiki-dark": "#DBEDFF", "--shiki-dark-text-decoration": "underline" })}">!note</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">] Optional title</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">&gt; body</span></span></code></pre></div><p>13 types: <code>note / info / tip / success / question / warning / failure / danger / bug / example / quote / abstract / todo</code>,plus aliases (<code>hint=tip</code>, <code>check=success</code>, <code>error=danger</code>...). Folding: <code>[!info]+</code> open by default, <code>[!info]-</code> closed. Nesting via <code>&gt; &gt; [!info]</code>.</p><h2 id="other-inline" tabindex="-1">Other inline <a class="header-anchor" href="#other-inline" aria-label="Permalink to &quot;Other inline&quot;">​</a></h2><ul><li><code>==highlight==</code> → <code>&lt;mark&gt;</code></li><li><code>%%comment%%</code> → stripped (not rendered)</li><li><code>[^id]</code> + standalone line <code>[^id]: text</code> → Pandoc footnotes</li><li>Trailing <code>^block-id</code> → adds <code>id=&quot;^block-id&quot;</code> to that block, URL hash jump works</li><li>Body <code>#tag</code> → links to <code>/_perspectives_/tags#tag</code></li></ul><h2 id="module-switches" tabindex="-1">Module switches <a class="header-anchor" href="#module-switches" aria-label="Permalink to &quot;Module switches&quot;">​</a></h2><p>Each can be disabled independently:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">  modules</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    wikilinks</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    embeds</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    callouts</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    highlight</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    comments</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    footnotes</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    blockRefs</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    views</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/docs/obsidian-syntax.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const obsidianSyntax = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  obsidianSyntax as default
};
