import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Views","description":"","frontmatter":{"title":"Views","sidebarTitle":"Views","order":5,"tags":["showcase","views","graph"]},"headers":[],"relativePath":"showcase/views.md","filePath":"showcase/views.md"}');
const _sfc_main = { name: "showcase/views.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_VaultGraph = resolveComponent("VaultGraph");
  const _component_VaultStats = resolveComponent("VaultStats");
  const _component_Tags = resolveComponent("Tags");
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="views" tabindex="-1">Views <a class="header-anchor" href="#views" aria-label="Permalink to &quot;Views&quot;">​</a></h1><p>The plugin scans your entire vault, automatically generates three interactive view components, and writes a <code>vault-data.json</code> for the frontend. Below the <strong>real components are embedded directly</strong> — they read this very site&#39;s own data.</p><div class="callout callout--tip" data-callout="tip"><div class="callout-title"><svg class="callout-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"></path><path d="M9 18h6"></path><path d="M10 22h4"></path></svg><span class="callout-title-text">These are live</span></div><div class="callout-content"><p>The graph, stats, and tags below are real components rendered live, not screenshots. Try dragging graph nodes, or clicking a tag to filter.</p></div></div><h2 id="relationship-graph-—-vaultgraph" tabindex="-1">Relationship graph — VaultGraph <a class="header-anchor" href="#relationship-graph-—-vaultgraph" aria-label="Permalink to &quot;Relationship graph — VaultGraph&quot;">​</a></h2><p>A D3 force-directed relationship graph: nodes are notes, edges are wikilink / transclusion relationships. It supports zooming (scroll wheel), dragging, hover-to-highlight neighbors, and click-to-navigate. When zoomed out, node names fade out automatically and emerge when zoomed in — consistent with Obsidian.</p><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;VaultGraph :max-nodes=&quot;500&quot; /&gt;</span></span></code></pre></div>`);
  _push(ssrRenderComponent(_component_VaultGraph, { "max-nodes": 300 }, null, _parent));
  _push(`<p>Node size varies with in-degree (how often it&#39;s linked to); dashed lines are transclusion edges, solid lines are ordinary wikilinks. Exceeding <code>max-nodes</code> shows a downgrade notice to keep performance.</p><h2 id="statistics-—-vaultstats" tabindex="-1">Statistics — VaultStats <a class="header-anchor" href="#statistics-—-vaultstats" aria-label="Permalink to &quot;Statistics — VaultStats&quot;">​</a></h2><p>A vault overview: counts of notes / tags / links / assets, plus a recently-updated list.</p><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;VaultStats /&gt;</span></span></code></pre></div>`);
  _push(ssrRenderComponent(_component_VaultStats, null, null, _parent));
  _push(`<h2 id="tag-cloud-—-tags" tabindex="-1">Tag cloud — Tags <a class="header-anchor" href="#tag-cloud-—-tags" aria-label="Permalink to &quot;Tag cloud — Tags&quot;">​</a></h2><p>All tags (frontmatter + body <code>#tag</code>) aggregated; click to filter the notes carrying that tag.</p><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;Tags /&gt;</span></span></code></pre></div>`);
  _push(ssrRenderComponent(_component_Tags, null, null, _parent));
  _push(`<h2 id="how-it-works" tabindex="-1">How it works <a class="header-anchor" href="#how-it-works" aria-label="Permalink to &quot;How it works&quot;">​</a></h2><ol><li>At build time it scans the vault and generates three pages — <code>graph.md</code> / <code>stats.md</code> / <code>tags.md</code> — under <code>&lt;srcDir&gt;/&lt;urlPrefix&gt;/</code>;</li><li>It writes <code>vault-data.json</code> into <code>public/</code> (nodes, edges, tags, stats, all included);</li><li>The three components are registered globally and render by reading <code>vault-data.json</code>;</li><li>These view pages are automatically attached to navigation (<code>injectInto</code>: nav dropdown / sidebar group / both).</li></ol><div class="callout callout--info" data-callout="info"><div class="callout-title"><svg class="callout-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M12 16v-4"></path><path d="M12 8h.01"></path></svg><span class="callout-title-text">Automatic injection</span></div><div class="callout-content"><p>This site attaches the views to the <strong>Perspectives</strong> entry in the top-right corner (default <code>injectInto: &#39;nav&#39;</code>). You can also have them appended to the end of every sidebar.</p></div></div><h2 id="related-config" tabindex="-1">Related config <a class="header-anchor" href="#related-config" aria-label="Permalink to &quot;Related config&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">  views</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    enabled</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: { </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">graph</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">stats</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">tags</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    urlPrefix</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;_perspectives_&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,        </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// directory for the view pages; &#39;&#39; = put at root</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    graphMaxNodes</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">500</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,                 </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// graph node limit</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    injectInto</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;nav&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,                  </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// &#39;nav&#39; | &#39;sidebar&#39; | &#39;both&#39; | &#39;off&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    parseInlineTags</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p>Back to the <a href="/vitepress-allyouneed/" class="wikilink" data-wikilink-target="index.md">showcase overview</a>, or read the <a href="/vitepress-allyouneed/guide/overview" class="wikilink" data-wikilink-target="guide/overview.md">full docs</a> →</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("showcase/views.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const views = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  views as default
};
