import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Obsidian 语法","description":"","frontmatter":{"title":"Obsidian 语法","sidebarTitle":"Obsidian 语法","order":5,"tags":["guide","syntax"]},"headers":[],"relativePath":"zh/guide/docs/obsidian-syntax.md","filePath":"zh/guide/docs/obsidian-syntax.md"}');
const _sfc_main = { name: "zh/guide/docs/obsidian-syntax.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="obsidian-语法" tabindex="-1">Obsidian 语法 <a class="header-anchor" href="#obsidian-语法" aria-label="Permalink to &quot;Obsidian 语法&quot;">​</a></h1><p>完整的语法 demo 在 <a href="/vitepress-allyouneed/tour/v0.3-tour" class="wikilink" data-wikilink-target="tour/v0.3-tour.md">v0.3 Tour</a>,这里只列规则。</p><h2 id="wikilinks" tabindex="-1">Wikilinks <a class="header-anchor" href="#wikilinks" aria-label="Permalink to &quot;Wikilinks&quot;">​</a></h2><table tabindex="0"><thead><tr><th>写法</th><th>含义</th></tr></thead><tbody><tr><td><code>[[note]]</code></td><td>普通链接</td></tr><tr><td><code>[[note|alias]]</code></td><td>自定义文本</td></tr><tr><td><code>[[note#heading]]</code></td><td>跳锚点</td></tr><tr><td><code>[[note#heading|alias]]</code></td><td>锚点 + 自定义文本</td></tr><tr><td><code>[[folder/note]]</code></td><td>路径形式</td></tr></tbody></table><p>frontmatter <code>aliases:</code> 也参与 wikilink 匹配。</p><h2 id="embeds" tabindex="-1">Embeds <a class="header-anchor" href="#embeds" aria-label="Permalink to &quot;Embeds&quot;">​</a></h2><table tabindex="0"><thead><tr><th>写法</th><th>渲染</th></tr></thead><tbody><tr><td><code>![[img.png]]</code> / <code>![[img.png|400]]</code> / <code>![[img.png|alt|400x300]]</code></td><td><code>&lt;img&gt;</code></td></tr><tr><td><code>![[clip.mp3]]</code></td><td><code>&lt;audio controls&gt;</code></td></tr><tr><td><code>![[movie.mp4|640x360]]</code></td><td><code>&lt;video controls&gt;</code></td></tr><tr><td><code>![[doc.pdf|800x900]]</code></td><td><code>&lt;iframe&gt;</code></td></tr><tr><td><code>![[note]]</code> / <code>![[note#heading]]</code></td><td>transclusion(内联整篇/节段)</td></tr></tbody></table><h2 id="callouts" tabindex="-1">Callouts <a class="header-anchor" href="#callouts" aria-label="Permalink to &quot;Callouts&quot;">​</a></h2><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">&gt; [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-light-text-decoration": "underline", "--shiki-dark": "#DBEDFF", "--shiki-dark-text-decoration": "underline" })}">!note</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">] Optional title</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">&gt; body</span></span></code></pre></div><p>13 种 type:<code>note / info / tip / success / question / warning / failure / danger / bug / example / quote / abstract / todo</code>,加别名(<code>hint=tip</code>, <code>check=success</code>, <code>error=danger</code>...)。折叠:<code>[!info]+</code> 默认开,<code>[!info]-</code> 默认关。嵌套用 <code>&gt; &gt; [!info]</code>。</p><h2 id="其它行内" tabindex="-1">其它行内 <a class="header-anchor" href="#其它行内" aria-label="Permalink to &quot;其它行内&quot;">​</a></h2><ul><li><code>==高亮==</code> → <code>&lt;mark&gt;</code></li><li><code>%%comment%%</code> → 删除(不渲染)</li><li><code>[^id]</code> + 单独一行的 <code>[^id]: text</code> → Pandoc 风格脚注</li><li>段落末尾 <code>^block-id</code> → 给该块加 <code>id=&quot;^block-id&quot;</code>,可被 URL hash 跳转</li><li>正文 <code>#tag</code> → 链到 <code>/_perspectives_/tags#tag</code></li></ul><h2 id="模块开关" tabindex="-1">模块开关 <a class="header-anchor" href="#模块开关" aria-label="Permalink to &quot;模块开关&quot;">​</a></h2><p>任一可独立关闭:</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">  modules</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    wikilinks</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    embeds</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    callouts</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    highlight</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    comments</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    footnotes</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    blockRefs</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    views</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("zh/guide/docs/obsidian-syntax.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const obsidianSyntax = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  obsidianSyntax as default
};
