import { resolveComponent, useSSRContext } from "vue";
import { ssrRenderAttrs, ssrRenderStyle, ssrRenderComponent } from "vue/server-renderer";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"三大视图","description":"","frontmatter":{"title":"三大视图","sidebarTitle":"三大视图","order":5,"tags":["showcase","views","graph"]},"headers":[],"relativePath":"zh/showcase/views.md","filePath":"zh/showcase/views.md"}');
const _sfc_main = { name: "zh/showcase/views.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  const _component_VaultGraph = resolveComponent("VaultGraph");
  const _component_VaultStats = resolveComponent("VaultStats");
  const _component_Tags = resolveComponent("Tags");
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="三大视图" tabindex="-1">三大视图 <a class="header-anchor" href="#三大视图" aria-label="Permalink to &quot;三大视图&quot;">​</a></h1><p>插件会扫描整个 vault,自动生成三个交互式视图组件,并写一份 <code>vault-data.json</code> 给前端。下面<strong>直接嵌入真实组件</strong>——它们读的就是这个站点自己的数据。</p><div class="callout callout--tip" data-callout="tip"><div class="callout-title"><svg class="callout-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"></path><path d="M9 18h6"></path><path d="M10 22h4"></path></svg><span class="callout-title-text">这些是活的</span></div><div class="callout-content"><p>下面的图谱、统计、标签都是实时渲染的真实组件,不是截图。试着拖拽图谱节点、点标签筛选。</p></div></div><h2 id="关系图-vaultgraph" tabindex="-1">关系图 VaultGraph <a class="header-anchor" href="#关系图-vaultgraph" aria-label="Permalink to &quot;关系图 VaultGraph&quot;">​</a></h2><p>D3 力导向关系图,节点是笔记,连线是 wikilink / 转译关系。支持缩放(滚轮)、拖拽、hover 高亮邻居、点击跳转。缩小时节点名自动淡出,放大时浮现 —— 和 Obsidian 一致。</p><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;VaultGraph :max-nodes=&quot;500&quot; /&gt;</span></span></code></pre></div>`);
  _push(ssrRenderComponent(_component_VaultGraph, { "max-nodes": 300 }, null, _parent));
  _push(`<p>节点大小按入度(被链接次数)变化;虚线是转译边、实线是普通 wikilink。超过 <code>max-nodes</code> 会显示降级提示以保证性能。</p><h2 id="统计-vaultstats" tabindex="-1">统计 VaultStats <a class="header-anchor" href="#统计-vaultstats" aria-label="Permalink to &quot;统计 VaultStats&quot;">​</a></h2><p>vault 概览:笔记 / 标签 / 链接 / 资源数量,加最近更新列表。</p><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;VaultStats /&gt;</span></span></code></pre></div>`);
  _push(ssrRenderComponent(_component_VaultStats, null, null, _parent));
  _push(`<h2 id="标签云-tags" tabindex="-1">标签云 Tags <a class="header-anchor" href="#标签云-tags" aria-label="Permalink to &quot;标签云 Tags&quot;">​</a></h2><p>所有标签(frontmatter + 正文 <code>#tag</code>)聚合,点击筛选出带该标签的笔记。</p><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;Tags /&gt;</span></span></code></pre></div>`);
  _push(ssrRenderComponent(_component_Tags, null, null, _parent));
  _push(`<h2 id="工作原理" tabindex="-1">工作原理 <a class="header-anchor" href="#工作原理" aria-label="Permalink to &quot;工作原理&quot;">​</a></h2><ol><li>构建时扫描 vault,在 <code>&lt;srcDir&gt;/&lt;urlPrefix&gt;/</code> 生成 <code>graph.md</code> / <code>stats.md</code> / <code>tags.md</code> 三个页面;</li><li>把 <code>vault-data.json</code> 写进 <code>public/</code>(节点、边、标签、统计一应俱全);</li><li>三个组件全局注册,读 <code>vault-data.json</code> 渲染;</li><li>这些视图页自动挂到导航(<code>injectInto</code>:nav 下拉 / sidebar 分组 / 两者)。</li></ol><div class="callout callout--info" data-callout="info"><div class="callout-title"><svg class="callout-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M12 16v-4"></path><path d="M12 8h.01"></path></svg><span class="callout-title-text">自动注入</span></div><div class="callout-content"><p>本站把视图挂在右上角 <strong>Perspectives</strong> 入口(默认 <code>injectInto: &#39;nav&#39;</code>)。你也可以让它追加到每个 sidebar 末尾。</p></div></div><h2 id="相关配置" tabindex="-1">相关配置 <a class="header-anchor" href="#相关配置" aria-label="Permalink to &quot;相关配置&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">  views</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    enabled</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: { </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">graph</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">stats</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">tags</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    urlPrefix</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;_perspectives_&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,        </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 视图页所在目录;&#39;&#39; = 放根目录</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    graphMaxNodes</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">500</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,                 </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 图谱节点上限</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    injectInto</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;nav&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,                  </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// &#39;nav&#39; | &#39;sidebar&#39; | &#39;both&#39; | &#39;off&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">    parseInlineTags</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p>回到 <a href="/vitepress-allyouneed/" class="wikilink" data-wikilink-target="index.md">展示总览</a>,或读 <a href="/vitepress-allyouneed/guide/overview" class="wikilink" data-wikilink-target="guide/overview.md">完整文档</a> →</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("zh/showcase/views.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const views = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  views as default
};
