/**
 * v0.2 — 在 srcDir 根目录生成 3 个虚拟视图 .md 文件。
 *
 * 设计原则:
 *   - **不覆盖用户文件**:目标文件已存在且没有我们的 sentinel,跳过 + 告警
 *   - **可重新生成**:存在但带 sentinel(说明上次是我们生成的)→ 覆盖,允许升级模板
 *   - **零依赖**:只用 node:fs,不引入新包
 *
 * 生成的 .md 走 VitePress 正常的扫描 → 路由 → 渲染流程,内部嵌入我们的 Vue 组件。
 */

import fs from 'node:fs'
import nodePath from 'node:path'
import type { ResolvedOptions, VaultIndex } from '../types.js'

export const VIEW_SENTINEL =
  '<!-- generated by vitepress-allyouneed (do not edit; will be regenerated) -->'

type ViewKind = 'graph' | 'stats' | 'tags'

interface ViewTemplate {
  kind: ViewKind
  fileName: string // 完整 .md 文件名
  title: string
  component: string // <VaultGraph /> 等
}

export interface GenerateMdReport {
  written: string[]
  skipped: { path: string; reason: string }[]
}

/**
 * 在 srcDir 根写视图 .md。返回报告供调用方打日志。
 */
export function generateViewMarkdown(
  options: ResolvedOptions,
  index: VaultIndex,
): GenerateMdReport {
  const report: GenerateMdReport = { written: [], skipped: [] }

  // 视图模块没开 → 直接返回
  if (!options.modules.views) return report

  const srcDir = nodePath.resolve(options.srcDir)
  const views = buildViewList(options)

  for (const v of views) {
    const target = nodePath.join(srcDir, v.fileName)

    // 已存在?判 sentinel
    if (fs.existsSync(target)) {
      let existing: string
      try {
        existing = fs.readFileSync(target, 'utf8')
      } catch {
        report.skipped.push({ path: target, reason: '文件不可读,跳过' })
        continue
      }
      if (!existing.includes(VIEW_SENTINEL)) {
        report.skipped.push({
          path: target,
          reason:
            `用户已有同名文件,不覆盖。要启用此视图请:` +
            `(a) 删除该文件 / (b) views.names.${v.kind} 改名 / (c) views.enabled.${v.kind}: false 关掉`,
        })
        continue
      }
      // 带 sentinel → 是我们之前生成的,允许覆盖(升级模板)
    }

    try {
      fs.writeFileSync(target, renderTemplate(v), 'utf8')
      report.written.push(target)
      // 把这个文件登记进 index,让我们自己的 resolver 也能解析它
      // (实际上 VaultScanner 下次 dev hot reload / build 时会自动 ingest)
      void index
    } catch (err) {
      report.skipped.push({
        path: target,
        reason: `写入失败: ${err instanceof Error ? err.message : String(err)}`,
      })
    }
  }

  return report
}

function buildViewList(options: ResolvedOptions): ViewTemplate[] {
  const { enabled, names, sidebarText } = options.views
  const list: ViewTemplate[] = []
  if (enabled.graph) {
    list.push({
      kind: 'graph',
      fileName: `${names.graph}.md`,
      title: sidebarText.graph,
      component: '<VaultGraph />',
    })
  }
  if (enabled.stats) {
    list.push({
      kind: 'stats',
      fileName: `${names.stats}.md`,
      title: sidebarText.stats,
      component: '<VaultStats />',
    })
  }
  if (enabled.tags) {
    list.push({
      kind: 'tags',
      fileName: `${names.tags}.md`,
      title: sidebarText.tags,
      component: '<Tags />',
    })
  }
  return list
}

function renderTemplate(v: ViewTemplate): string {
  return [
    VIEW_SENTINEL,
    '---',
    `title: ${v.title}`,
    'layout: doc',
    'aside: false',
    'outline: false',
    '---',
    '',
    `# ${v.title}`,
    '',
    v.component,
    '',
  ].join('\n')
}
