/**
 * v0.2 — 在 srcDir 根目录生成 3 个虚拟视图 .md 文件。
 *
 * - 不覆盖用户文件:已存在且没我们的 sentinel,跳过 + 告警
 * - 可重新生成:存在但带 sentinel(说明上次是我们生成的),允许覆盖升级模板
 */

import fs from 'node:fs'
import nodePath from 'node:path'
import type { ResolvedOptions, VaultIndex } from '../types.js'

export const VIEW_SENTINEL =
  '<!-- generated by vitepress-allyouneed (do not edit; will be regenerated) -->'

type ViewKind = 'graph' | 'stats' | 'tags'

interface ViewTemplate {
  kind: ViewKind
  fileName: string
  title: string
  component: string
}

export interface GenerateMdReport {
  written: string[]
  skipped: { path: string; reason: string }[]
}

export function generateViewMarkdown(
  options: ResolvedOptions,
  index: VaultIndex,
): GenerateMdReport {
  const report: GenerateMdReport = { written: [], skipped: [] }
  if (!options.modules.views) return report

  const srcDir = nodePath.resolve(options.srcDir)
  const prefix = options.views.urlPrefix
  const viewDir = prefix ? nodePath.join(srcDir, prefix) : srcDir

  // 子目录方式时,先建目录
  if (prefix) {
    try {
      fs.mkdirSync(viewDir, { recursive: true })
    } catch {
      /* mkdir 失败下面 write 也会失败,统一在那里报 */
    }
  }

  const views = buildViewList(options)

  for (const v of views) {
    const target = nodePath.join(viewDir, v.fileName)

    if (fs.existsSync(target)) {
      let existing: string
      try {
        existing = fs.readFileSync(target, 'utf8')
      } catch {
        report.skipped.push({ path: target, reason: 'file not readable, skipping' })
        continue
      }
      if (!existing.includes(VIEW_SENTINEL)) {
        report.skipped.push({
          path: target,
          reason:
            `user-owned file present (no sentinel), not overwriting. To enable this view: ` +
            `(a) delete the file, (b) rename via views.names.${v.kind}, or (c) disable via views.enabled.${v.kind}: false`,
        })
        continue
      }
    }

    try {
      fs.writeFileSync(target, renderTemplate(v), 'utf8')
      report.written.push(target)
      void index
    } catch (err) {
      report.skipped.push({
        path: target,
        reason: `write failed: ${err instanceof Error ? err.message : String(err)}`,
      })
    }
  }

  return report
}

function buildViewList(options: ResolvedOptions): ViewTemplate[] {
  const { enabled, names, sidebarText, graphMaxNodes } = options.views
  const list: ViewTemplate[] = []
  if (enabled.graph) {
    list.push({
      kind: 'graph',
      fileName: `${names.graph}.md`,
      title: sidebarText.graph,
      // 把配置里的 graphMaxNodes 直接注入到组件 prop
      component: `<VaultGraph :max-nodes="${graphMaxNodes}" />`,
    })
  }
  if (enabled.stats) {
    list.push({
      kind: 'stats',
      fileName: `${names.stats}.md`,
      title: sidebarText.stats,
      component: '<VaultStats />',
    })
  }
  if (enabled.tags) {
    list.push({
      kind: 'tags',
      fileName: `${names.tags}.md`,
      title: sidebarText.tags,
      component: '<Tags />',
    })
  }
  return list
}

function renderTemplate(v: ViewTemplate): string {
  // 关键:frontmatter `---` 必须是文件**第一行**,否则 VitePress / gray-matter
  // 不识别。sentinel HTML 注释放到 frontmatter 之后。
  // 视图页全屏展示 — sidebar/aside/outline 都隐藏,只剩中间 graph/stats/tags 组件
  return [
    '---',
    `title: ${v.title}`,
    'layout: doc',
    'sidebar: false',
    'aside: false',
    'outline: false',
    '---',
    '',
    VIEW_SENTINEL,
    '',
    `# ${v.title}`,
    '',
    v.component,
    '',
  ].join('\n')
}
