/**
 * v0.3.9 — sidebar materialize:把"自动生成 sidebar"物化成每文件夹的 `_sidebar.md`。
 *
 * 行为:
 *   - 默认关 (`materialize: 'off'`)。开启 (`top-level` / `all`) 后,
 *     扫描期为目标文件夹生成 `_sidebar.md`,内容是:
 *
 *     ```yaml
 *     ---
 *     # sidebarAuto:                  (optional override; uncomment to use)
 *     #   sortBy: title
 *     #   foldersFirst: true
 *     #   stripNumericPrefix: false
 *     ---
 *     <!-- generated by vitepress-allyouneed/sidebar-materialize -->
 *
 *     - {.}
 *     ```
 *
 *   - `- {.}` 占位符在 build 时由 parse-sidebar-md.ts 重展开 → 自动适配新文件
 *   - **sentinel 保护**:用户编辑后去掉 sentinel,该文件从此被视为完全手工,
 *     插件不再动它(同 autoFolderIndex 行为)
 *   - 已有用户写的、不含 sentinel 的 `_sidebar.md` 永不覆盖
 *
 * 跟 autoFolderIndex 的区别:autoFolderIndex 生成"目录页面"(index.md,供用户访问
 * `/folder/` URL 看到),materialize 生成"sidebar 配置文件"(_sidebar.md,定义
 * 这个文件夹的 sidebar 结构)。两者**独立**,可一起开。
 */

import fs from 'node:fs'
import nodePath from 'node:path'
import type { ResolvedOptions } from '../types.js'

export const SIDEBAR_MATERIALIZE_SENTINEL =
  '<!-- generated by vitepress-allyouneed/sidebar-materialize (do not edit if you want auto-refresh; remove this comment to take ownership) -->'

export type MaterializeMode = 'off' | 'top-level' | 'all'

export interface MaterializeReport {
  written: string[]
  skipped: { path: string; reason: string }[]
}

const MD_RE = /\.(md|markdown)$/i
const SIDEBAR_RE = /^_sidebar\.(md|markdown)$/i

export interface MaterializeOptions {
  mode?: MaterializeMode
  /** 排除文件夹(相对 srcDir,glob)。默认 [] */
  exclude?: string[]
}

export function generateSidebarMaterializations(
  options: ResolvedOptions,
  matOpts: MaterializeOptions = {},
): MaterializeReport {
  const report: MaterializeReport = { written: [], skipped: [] }
  const mode = matOpts.mode ?? 'off'
  if (mode === 'off') return report

  const srcDir = nodePath.resolve(options.srcDir)
  const viewsPrefix = options.views.urlPrefix
    ? options.views.urlPrefix.replace(/^\/+|\/+$/g, '')
    : ''
  const exclude = matOpts.exclude ?? []

  // 收集要处理的目录(根 + 各级,模仿 generate-folder-index)
  const dirs = [srcDir, ...collectDirs(srcDir, srcDir, viewsPrefix, exclude, mode)]
  for (const dirAbs of dirs) {
    const target = nodePath.join(dirAbs, '_sidebar.md')
    if (fs.existsSync(target)) {
      let content: string
      try {
        content = fs.readFileSync(target, 'utf8')
      } catch {
        report.skipped.push({ path: target, reason: 'file unreadable, skipping' })
        continue
      }
      if (!content.includes(SIDEBAR_MATERIALIZE_SENTINEL)) {
        report.skipped.push({
          path: target,
          reason:
            'user-owned _sidebar.md (no sentinel), not overwriting. ' +
            'Add `' + SIDEBAR_MATERIALIZE_SENTINEL + '` to opt back into auto-refresh.',
        })
        continue
      }
      // 含 sentinel → 允许覆盖(刷新模板)
    }
    // 空目录(没任何 .md / 子目录里也没 .md)→ 跳过
    if (!hasAnyMd(dirAbs)) {
      continue
    }
    try {
      fs.writeFileSync(target, defaultTemplate(), 'utf8')
      report.written.push(target)
    } catch (err) {
      report.skipped.push({
        path: target,
        reason: `write failed: ${err instanceof Error ? err.message : String(err)}`,
      })
    }
  }
  return report
}

function defaultTemplate(): string {
  return [
    '---',
    '# Override sidebar rules for this folder (uncomment to use):',
    '# sidebarAuto:',
    '#   sortBy: title             # order-then-title | title | mtime-desc',
    '#   collapsed: true           # default group collapsed?',
    '#   foldersFirst: false       # folders before files',
    '#   stripNumericPrefix: true',
    '#   stripNumericPrefixSeparators: "-_\\\\s"',
    '#   hiddenKey: sidebarHidden',
    '#   titleKey: sidebarTitle',
    '#   orderKey: order',
    '---',
    SIDEBAR_MATERIALIZE_SENTINEL,
    '',
    '<!-- `- {.}` expands to this folder\'s contents (files first, then subfolder groups). ',
    '     Customize freely — split into named groups, add manual links, etc. ',
    '     The `{.}` placeholder re-resolves each build, so new files appear automatically. ',
    '     See DOCS.md "_sidebar.md folder placeholder" for the full syntax. -->',
    '',
    '- {.}',
    '',
  ].join('\n')
}

function collectDirs(
  root: string,
  cur: string,
  viewsPrefix: string,
  exclude: string[],
  mode: MaterializeMode,
): string[] {
  const out: string[] = []
  walk(cur, 0)
  return out
  function walk(dir: string, depth: number): void {
    if (mode === 'top-level' && depth > 1) return
    let entries: fs.Dirent[]
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue
      if (e.name.startsWith('.') || e.name.startsWith('_')) continue
      if (e.name === 'node_modules' || e.name === 'public') continue
      const full = nodePath.join(dir, e.name)
      const rel = nodePath.relative(root, full).split(nodePath.sep).join('/')
      if (viewsPrefix && (rel === viewsPrefix || rel.startsWith(viewsPrefix + '/'))) continue
      if (exclude.some((pat) => matchGlob(rel, pat))) continue
      out.push(full)
      if (mode === 'all') walk(full, depth + 1)
    }
  }
}

function hasAnyMd(dir: string): boolean {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const e of entries) {
      if (e.isFile() && MD_RE.test(e.name) && !SIDEBAR_RE.test(e.name)) return true
      if (e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.')) {
        if (hasAnyMd(nodePath.join(dir, e.name))) return true
      }
    }
  } catch {
    /* ignore */
  }
  return false
}

function matchGlob(path: string, pat: string): boolean {
  const ESC = /[.+?^${}()|[\]\\]/g
  const re = pat
    .replace(ESC, '\\$&')
    .replace(/\*\*/g, '__DS__')
    .replace(/\*/g, '[^/]*')
    .replace(/__DS__/g, '.*')
  return new RegExp('^' + re + '$').test(path)
}
