/**
 * v0.3 — 给缺 index.md / README.md 的文件夹自动生成 index 页。
 *
 * 行为:
 *   - 扫 srcDir 下所有目录,对**已有 .md 文件**但**无 index.md/README.md**的
 *     目录,生成一个简单的 index.md
 *   - 内容:H1 = 目录名 humanized;然后列出直接子文件 + 子目录链接(用 wikilink)
 *   - 用 sentinel 标记,下次升级时允许覆盖
 *   - 不生成:`_` 前缀目录、views.urlPrefix 目录、根目录(根用户自己写 index)
 *
 * 时机:在 vault scan 之前调用(views generate-md 同期),让 scanVault 看到这些
 * 生成的 index,sidebar 自动识别为 group link。
 */

import fs from 'node:fs'
import nodePath from 'node:path'
import type { ResolvedOptions } from '../types.js'

export const FOLDER_INDEX_SENTINEL =
  '<!-- generated by vitepress-allyouneed/folder-index (do not edit; will be regenerated) -->'

export interface FolderIndexReport {
  written: string[]
  skipped: { path: string; reason: string }[]
}

export type FolderIndexMode = 'off' | 'top-level' | 'all'

export interface FolderIndexOptions {
  /**
   * 三种模式:
   *   - 'off'        完全不生成
   *   - 'top-level'  只为**顶级目录**生成(即作为 nav tab 入口的那批),
   *                  侧边栏内的子目录保持原版"点击展开"(不跳转)行为
   *   - 'all'        所有非空目录都生成
   *
   * 默认 'top-level' —— 既保证 nav tab 能正确跳转,又不在所有子目录里写文件。
   */
  mode?: FolderIndexMode
  /** 排除的 dir(相对 srcDir,glob)。默认 [] */
  exclude?: string[]
  /** 模板生成函数,可覆盖 */
  template?: (ctx: TemplateContext) => string
  /** humanize 时剥 `01-foo` 等数字前缀,默认 true */
  stripNumericPrefix?: boolean

  /** @deprecated 老 v0.3 字段,等价 mode: enabled?'top-level':'off' */
  enabled?: boolean
}

export interface TemplateContext {
  dirAbsPath: string
  dirRelPath: string
  /** 目录名(已 humanize) */
  title: string
  /** 直接子 .md 文件(相对该目录) */
  files: Array<{ name: string; relPath: string; title: string }>
  /** 直接子目录(已有内容的) */
  subDirs: Array<{ name: string; title: string }>
}

const MD_RE = /\.(md|markdown)$/i
const INDEX_RE = /^(index|README)\.(md|markdown)$/i

export function generateFolderIndexes(
  options: ResolvedOptions,
  folderOpts: FolderIndexOptions = {},
): FolderIndexReport {
  const report: FolderIndexReport = { written: [], skipped: [] }

  // 兼容 enabled / 推断 mode
  const mode: FolderIndexMode =
    folderOpts.mode ??
    (folderOpts.enabled === true
      ? 'top-level'
      : folderOpts.enabled === false
        ? 'off'
        : 'top-level')
  if (mode === 'off') return report

  const srcDir = nodePath.resolve(options.srcDir)
  const viewsPrefix = options.views.urlPrefix
    ? options.views.urlPrefix.replace(/^\/+|\/+$/g, '')
    : ''
  const strip = folderOpts.stripNumericPrefix ?? true
  const exclude = folderOpts.exclude ?? []
  const template = folderOpts.template ?? defaultTemplate

  // 收集要处理的目录;0.3.2:把 srcDir 根**也加进去**,
  // 避免用户没写 index.md 时 / 直接 404
  const dirsToProcess = [srcDir, ...collectDirs(srcDir, srcDir, viewsPrefix, exclude, mode)]

  for (const dirAbs of dirsToProcess) {
    const dirRel = nodePath.relative(srcDir, dirAbs).split(nodePath.sep).join('/')
    // 0.3.2:**根目录也生成**(模板会用 srcDir name 当标题)

    const entries = safeReaddir(dirAbs)
    if (entries.length === 0) continue

    // 检测候选 dirIndex 文件:
    //   1. 与文件夹同名的 .md(优先级最高,优先于 index/README)
    //   2. index.md
    //   3. README.md
    // 任一存在且**不是我们之前生成的**(没 sentinel)→ 跳过,把现成的当索引页
    const dirName = nodePath.basename(dirAbs).toLowerCase()
    const target = nodePath.join(dirAbs, 'index.md')

    let userHasOwnIndex = false
    let userIndexName = ''
    for (const e of entries) {
      if (!e.isFile()) continue
      const lower = e.name.toLowerCase()
      const isCandidate =
        lower === `${dirName}.md` ||
        lower === `${dirName}.markdown` ||
        INDEX_RE.test(e.name)
      if (!isCandidate) continue
      const content = safeRead(nodePath.join(dirAbs, e.name))
      if (content === null) continue
      // 用户文件(包括空 frontmatter-only 文件)都不覆盖。
      // 只有带 sentinel 的我们自己生成的旧文件才允许覆盖更新。
      if (!content.includes(FOLDER_INDEX_SENTINEL)) {
        userHasOwnIndex = true
        userIndexName = e.name
        break
      }
    }
    if (userHasOwnIndex) {
      // 用户自己加了 dirIndex(同名或 index/README)。若我们之前曾生成过
      // index.md / README.md(带 sentinel),清理掉,避免 sidebar 同时出现
      // "用户文件" + "我们的旧生成"两条 stale item。
      for (const candName of ['index.md', 'README.md']) {
        if (candName.toLowerCase() === userIndexName.toLowerCase()) continue
        const candPath = nodePath.join(dirAbs, candName)
        const candContent = safeRead(candPath)
        if (candContent && candContent.includes(FOLDER_INDEX_SENTINEL)) {
          try {
            fs.unlinkSync(candPath)
            report.skipped.push({
              path: candPath,
              reason: `被用户的 ${userIndexName} 取代,自动清理`,
            })
          } catch {
            /* 删失败就保留,不影响主流程 */
          }
        }
      }
      report.skipped.push({
        path: target,
        reason: `用户已有 ${userIndexName},不生成`,
      })
      continue
    }

    // 收集子文件 + 子目录
    const files: TemplateContext['files'] = []
    const subDirs: TemplateContext['subDirs'] = []
    for (const e of entries) {
      if (e.isFile() && MD_RE.test(e.name) && !INDEX_RE.test(e.name)) {
        const name = e.name.replace(MD_RE, '')
        files.push({
          name,
          relPath: name,
          title: humanize(name, strip),
        })
      } else if (e.isDirectory() && !e.name.startsWith('_')) {
        // 排除空子目录
        if (hasMdContent(nodePath.join(dirAbs, e.name))) {
          subDirs.push({ name: e.name, title: humanize(e.name, strip) })
        }
      }
    }

    // 空目录(子文件 + 子目录都为 0)→ 不生成
    if (files.length === 0 && subDirs.length === 0) {
      continue
    }

    files.sort((a, b) => a.title.localeCompare(b.title))
    subDirs.sort((a, b) => a.title.localeCompare(b.title))

    // 根目录(dirRel === '')用 srcDir basename 当 title;否则用最后一段
    const lastSeg =
      dirRel === ''
        ? nodePath.basename(srcDir)
        : dirRel.split('/').pop() ?? ''
    const ctx: TemplateContext = {
      dirAbsPath: dirAbs,
      dirRelPath: dirRel,
      title: humanize(lastSeg, strip) || 'Home',
      files,
      subDirs,
    }

    try {
      fs.writeFileSync(target, template(ctx), 'utf8')
      report.written.push(target)
    } catch (err) {
      report.skipped.push({
        path: target,
        reason: `写入失败: ${err instanceof Error ? err.message : String(err)}`,
      })
    }
  }

  return report
}

function collectDirs(
  root: string,
  cur: string,
  viewsPrefix: string,
  exclude: string[],
  mode: FolderIndexMode,
): string[] {
  const out: string[] = []
  walk(cur, 0)
  return out

  function walk(dir: string, depth: number): void {
    // top-level 模式只收 depth 0 的直接子目录
    if (mode === 'top-level' && depth > 1) return

    let entries: fs.Dirent[]
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true })
    } catch {
      return
    }
    for (const e of entries) {
      if (!e.isDirectory()) continue
      if (e.name.startsWith('.')) continue
      if (e.name.startsWith('_')) continue
      if (e.name === 'node_modules' || e.name === 'public') continue
      const full = nodePath.join(dir, e.name)
      const rel = nodePath.relative(root, full).split(nodePath.sep).join('/')
      if (viewsPrefix && (rel === viewsPrefix || rel.startsWith(viewsPrefix + '/'))) continue
      if (exclude.some((pat) => matchGlob(rel, pat))) continue
      out.push(full)
      if (mode === 'all') walk(full, depth + 1)
    }
  }
}

function hasMdContent(dir: string): boolean {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const e of entries) {
      if (e.isFile() && MD_RE.test(e.name)) return true
      if (e.isDirectory() && !e.name.startsWith('_') && !e.name.startsWith('.')) {
        if (hasMdContent(nodePath.join(dir, e.name))) return true
      }
    }
  } catch {
    /* ignore */
  }
  return false
}

function safeReaddir(dir: string): fs.Dirent[] {
  try {
    return fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return []
  }
}

function safeRead(p: string): string | null {
  try {
    return fs.readFileSync(p, 'utf8')
  } catch {
    return null
  }
}

function matchGlob(path: string, pat: string): boolean {
  const ESC = /[.+?^${}()|[\]\\]/g
  const re = pat
    .replace(ESC, '\\$&')
    .replace(/\*\*/g, '__DS__')
    .replace(/\*/g, '[^/]*')
    .replace(/__DS__/g, '.*')
  return new RegExp('^' + re + '$').test(path)
}

/** 文件夹名 humanize:`my-dir` / `01-foo_bar` → `My Dir` / `Foo Bar`(开 strip 时) */
export function humanize(name: string, stripNumeric: boolean): string {
  let s = name
  if (stripNumeric) {
    s = s.replace(/^\d+[-_.\s]+/, '')
  }
  return s
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (m) => m.toUpperCase())
}

function defaultTemplate(ctx: TemplateContext): string {
  const lines: string[] = []
  lines.push('---')
  lines.push(`title: ${ctx.title}`)
  lines.push(`sidebarTitle: ${ctx.title}`)
  lines.push('---')
  lines.push(FOLDER_INDEX_SENTINEL)
  lines.push('')
  lines.push(`# ${ctx.title}`)
  lines.push('')
  if (ctx.subDirs.length > 0) {
    lines.push('## Sections')
    lines.push('')
    for (const d of ctx.subDirs) {
      lines.push(`- [[${ctx.dirRelPath}/${d.name}/|${d.title}]]`)
    }
    lines.push('')
  }
  if (ctx.files.length > 0) {
    lines.push('## Pages')
    lines.push('')
    for (const f of ctx.files) {
      lines.push(`- [[${ctx.dirRelPath}/${f.relPath}|${f.title}]]`)
    }
    lines.push('')
  }
  return lines.join('\n')
}
